---
- name: Check the alternatives list
  block:

    - name: "Check alternatives for {{ alt.key }}"
      ansible.builtin.assert:
        that:
          - alternative.state is defined
          - alternative.state is regex('^present|absent$')
          - alternative.path is defined
          - alternative.path is regex('^\/')
          - alternative.path | type_debug is regex('^str|AnsibleUnicode|AnsibleUnsafeText$')
      loop: "{{ alt.value.alternatives }}"
      loop_control:
        loop_var: alternative
        label: "{{ alternative.path }}"

    - name: "Check alternatives for {{ alt.key }}"
      ansible.builtin.include_tasks: alternative_checks.yml
      when: alternative.state == "present"
      loop: "{{ alt.value.alternatives }}"
      loop_control:
        loop_var: alternative
        label: "{{ alternative.path }}"

  tags:
    - alternatives
...
