# Copyright 2022-2025 Chris Croome
#
# This file is part of the Webarchitects Debian alternatives Ansible role.
#
# The Webarchitects Debian alternatives Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Debian alternatives Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Debian alternatives Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Generate lists of alternatives present and absent
  block:

    - name: Generate an array of alternatives present for Ansible < 2.13.0
      ansible.builtin.set_fact:
        alternatives_present: "{{ alternatives_present | default([]) }} + ['{{ alt_update.name }}']"
      when:
        - ansible_version.full is version('2.13.0', '<')
        - ( alt_update.state is not defined ) or ( alt_update.state == "present" )
      loop: "{{ alternatives_update }}"
      loop_control:
        loop_var: alt_update
        label: "{{ alt_update.name }}"

    - name: Generate an array of alternatives present for Ansible >= 2.13.0
      ansible.builtin.set_fact:
        alternatives_present: "{{ alternatives_present | default([]) + [alt_update.name] }}"
      when:
        - ansible_version.full is version('2.13.0', '>=')
        - ( alt_update.state is not defined ) or ( alt_update.state == "present" )
      loop: "{{ alternatives_update }}"
      loop_control:
        loop_var: alt_update
        label: "{{ alt_update.name }}"

    - name: Debug alternatives present array
      ansible.builtin.debug:
        var: alternatives_present
        verbosity: 2
      when: alternatives_present is defined

    - name: Generate an array of alternatives absent for Ansible < 2.13.0
      ansible.builtin.set_fact:
        alternatives_absent: "{{ alternatives_absent | default([]) }} + ['{{ alt_update.name }}']"
      when:
        - ansible_version.full is version('2.13.0', '<')
        - ( alt_update.state is defined ) and ( alt_update.state == "absent" )
      loop: "{{ alternatives_update }}"
      loop_control:
        loop_var: alt_update
        label: "{{ alt_update.name }}"

    - name: Generate an array of alternatives absent for Ansible >= 2.13.0
      ansible.builtin.set_fact:
        alternatives_absent: "{{ alternatives_absent | default([]) + [alt_update.name] }}"
      when:
        - ansible_version.full is version('2.13.0', '>=')
        - ( alt_update.state is defined ) and ( alt_update.state == "absent" )
      loop: "{{ alternatives_update }}"
      loop_control:
        loop_var: alt_update
        label: "{{ alt_update.name }}"

    - name: Debug alternatives absent array
      ansible.builtin.debug:
        var: alternatives_absent
        verbosity: 2
      when: alternatives_absent is defined

  when: ( alternatives_update is defined ) and ( alternatives_update != {} )
  tags:
    - alternatives
...
