---
- name: Check alternatives variables
  block:

    - name: Check that alternatives and alternative_facts are booleans
      assert:
        that:
          - alternatives | type_debug == "bool"
          - alternative_facts | type_debug == "bool"

    - name: Check alternatives_update dictionary
      block:

        - name: Check that alternatives_update is a dictionary
          assert:
            that:
              - alternatives_update | type_debug == "dict"

        - name: Check alternatives names
          assert:
            that:
              - ZZ
          loop: "{{ alternatives_update  | dict2items }}"
          loop_control:
            loop_var: alt
            label: "{{ alt.key }}"

      when: alternatives_update is defined

  tags:
    - alternatives
...
