---
- name: Check a path
  block:

    - name: Check path is defined
      ansible.builtin.assert:
        that:
          - path is defined
          - path is regex('^\/')
          - path | type_debug is regex('^AnsibleUnicode|AnsibleUnsafeText|str$')

    - name: Check path exists
      ansible.builtin.stat:
        path: "{{ path }}"
      register: alternatives_path

    - name: Fail if path doesn't exist"
      ansible.builtin.assert:
        that:
          - alternatives_path.stat.exists
        fail_msg: "The file {{ path }} doesn't exist"

  tags:
    - alternatives
...
