---
- name: Check alternatve slaves
  block:

    - name: Debug slave
      ansible.builtin.debug:
        var: slave
        verbosity: 2

    - name: Check slave name is defined
      ansible.builtin.assert:
        that:
          - slave.name is defined
          - slave.name | type_debug is regex('^AnsibleUnicode|AnsibleUnsafeText|str$')

    - name: Check slave state is defined
      ansible.builtin.assert:
        that:
          - slave.state is regex('^present|absent$')
      when: slave.state is defined

    - name: Check slave path
      ansible.builtin.include_tasks: check_path.yml
      vars:
        path: "{{ slave.path }}"
      when: ( slave.state is not defined ) or ( slave.state == "present" )

  tags:
    - alternatives
...
