---
- name: Check a path
  block:

    - name: Check path is defined
      ansible.builtin.assert:
        that:
          - path is defined
          - path is regex('^\/')
          - path | type_debug is regex('^AnsibleUnicode|AnsibleUnsafeText|str$')
        quiet: "{% if ansible_check_mode or ansible_verbosity >= 1 %}false{% else %}true{% endif %}"

    - name: Check path exists
      ansible.builtin.stat:
        path: "{{ path }}"
      register: alternatives_path

    - name: Fail if path doesn't exist
      ansible.builtin.assert:
        that:
          - alternatives_path.stat.exists
        quiet: "{% if ansible_check_mode or ansible_verbosity >= 1 %}false{% else %}true{% endif %}"
        fail_msg: "The file {{ path }} doesn't exist"

    # - name: Warn that path doesn't exist
    #   ansible.builtin.debug:
    #     msg: "The file {{ path }} doesn't exist"

  tags:
    - alternatives
...
