---
- name: Checks for present alternative
  block:

    - name: Debug alternative
      debug:
        var: alt
        verbosity: 2

    - name: Check alternative name
      assert:
        that:
          - alt.alternative is defined
          - alt.alternative | type_debug is regex('AnsibleUnicode|AnsibleUnsafeText|str')

    - name: Check alternative state
      assert:
        that:
          - alt.state is regex('^present|absent$')
      when: alt.state is defined

    - name: Check alternative link
      include_tasks: check_path.yml
      vars:
        path: "{{ alt.alternative }}"
      when: ( alt.state is not defined ) or ( alt.state == "present" )

    - name: Check alternative priority
      assert:
        that:
          - alt.priority | type_debug == "int"
          - alt.priority is regex('^[0-9]{1,4}$')

    - name: Check alternative slaves
      block:

        - name: Check that alternative slaves is a array
          assert:
            that:
              - alt.slaves | type_debug == "list"

        - name: Include checks for alternative slaves when present
          include_tasks: check_slave.yml
          loop: "{{ alt.slaves }}"
          loop_control:
            loop_var: slave
            label: "{{ slave.name }}"
          when: alt.slaves != []

      when: alt.slaves is defined

  tags:
    - alternatives
...
