---
- name: Check alternatives variables
  block:

    - name: Check that alternatives and alternative_facts are booleans
      assert:
        that:
          - alternatives | type_debug == "bool"
          - alternative_facts | type_debug == "bool"

    - name: Check alternatives_update dictionary
      block:

        - name: Check that alternatives_update is a dictionary
          assert:
            that:
              - alternatives_update | type_debug == "dict"

        - name: Check alternative state
          assert:
            that:
              - alt.value.state is defined
              - alt.value.state is regex('^absent|present$')
          loop: "{{ alternatives_update  | dict2items }}"
          loop_control:
            loop_var: alt
            label: "{{ alt.key }}"

        - name: Check alternative link and alternatives when present
          assert:
            that:
              - alt.value.link is defined
              - alt.value.link is regex('^\/')
              - alt.value.link | type_debug is regex('^str|AnsibleUnicode|AnsibleUnsafeText$')
              - alt.value.alternatives is defined
              - alt.value.alternatives | type_debug == "list"
          loop: "{{ alternatives_update  | dict2items }}"
          loop_control:
            loop_var: alt
            label: "{{ alt.key }}"
          when: alt.value.state == "present"

        - name: Include checks for the lists of alternatives present
          include_tasks: alternatives_checks.yml
          loop: "{{ alternatives_update  | dict2items }}"
          loop_control:
            loop_var: alt
            label: "{{ alt.key }}"
          when: alt.value.state == "present"

      when: alternatives_update is defined

  tags:
    - alternatives
...
