---
- name: Check alternatives variables
  block:

    - name: Check that alternatives and alternative_facts are booleans
      ansible.builtin.assert:
        that:
          - alternatives | type_debug == "bool"
          - alternative_facts | type_debug == "bool"

    - name: Check alternatives_update list
      block:

        - name: Debug alternatives to update
          debug:
            var: alternatives_update
            verbosity: 2

        - name: Check that alternatives_update is a array
          assert:
            that:
              - alternatives_update | type_debug == "list"

        - name: Include checks for the alternatives present if they don't match existing alternatives
          include_tasks: check_alternatives.yml
          when: alt_update != ansible_local.update_alternatives.selections[alt_update.name]
          loop: "{{ alternatives_update }}"
          loop_control:
            loop_var: alt_update
            label: "{{ alt_update }}"

      when: alternatives_update is defined

  tags:
    - alternatives
...
