---
- name: Ansible alternatives local facts
  block:

    - name: Required packages present
      ansible.builtin.apt:
        pkg:
          - jo
        state: present

    - name: Ansible facts.d directory present
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        recurse: true
        state: directory
        mode: 0700
        owner: root
        group: root

    - name: Ansible alternatives local facts script present
      copy:
        src: alternatives.fact
        dest: /etc/ansible/facts.d/alternatives.fact
        mode: 0700
        owner: root
        group: root
      register: alternatives_facts

    - name: Include tasks to generate alternatives present and alternatives absent tasks
      include_tasks: alternatives.yml
      when: ( alternatives_update is defined ) and ( alternatives_update != {} )

    - name: Alternatives present in facts config file
      lineinfile:
        path: /etc/ansible/alternatives
        line: "{{ alt }}"
        state: present
        create: true
        mode: 0600
        owner: root
        group: root
      loop: "{{ alternatives_present }}"
      loop_control:
        loop_var: alt
        label: "{{ alt }}"
      when: ( alternatives_present is defined ) and ( alternatives_present != [] )
      notify: Update ansible_local

    - name: Alternatives absent from facts config file
      lineinfile:
        path: /etc/ansible/alternatives
        line: "{{ alt }}"
        state: absent
        create: true
        mode: 0600
        owner: root
        group: root
      loop: "{{ alternatives_absent }}"
      loop_control:
        loop_var: alt
        label: "{{ alt }}"
      when: ( alternatives_absent is defined ) and ( alternatives_absent != [] )
      notify: Update ansible_local

  tags:
    - alternatives
...
