---
- name: Debug slave
  debug:
    msg:
      - "alt_update.link {{ alt_update.link }}"
      - "alt_slave.name {{ alt_slave.name }}"
      - "alt_slave.path: {{ alt_slave.path }}"
      - "slave.name {{ slave.name }}"
      - "slave.path {{ slave.path }}"
    verbosity: 2
  when: slave.name == alt_slave.name
  loop: "{{ alternative.slaves }}"
  loop_control:
    loop_var: alt_slave
    label: "{{ alt_slave.name }}"
  tags:
    - alternatives

- name: "Set a variable for the slaves part of the update-alternatives command for {{ alt_update.name }} alternative {{ alternative.alternative }}"
  set_fact:
    alternative_slaves: "{{ alternative_slaves | default('') }} --slave {{ alt_update.link | quote }} {{ slave.name | quote }} {{ slave.path | quote }}"
  when: slave.name == alt_slave.name
  loop: "{{ alternative.slaves }}"
  loop_control:
    loop_var: alt_slave
    label: "{{ alt_slave.name }}"
  tags:
    - alternatives
...
