# Copyright 2022-2023 Chris Croome
#
# This file is part of the Webarchitects Debian alternatives Ansible role.
#
# The Webarchitects Debian alternatives Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Debian alternatives Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Debian alternatives Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Update alternatives
  block:

    - name: "Check alternative {{ alt_update.name }} absent"
      ansible.builtin.debug:
        msg: "update-alternatives --remove-all {{ alt_update.name }}"
      when:
        - ( ansible_check_mode ) or ( ansible_verbosity >= 1 )
        - ( alt_update.state is defined ) and ( alt_update.state == "absent" )
        - ansible_local.update_alternatives.selections[alt_update.name] is defined

    - name: "Alternative {{ alt_update.name }} absent"
      community.general.alternatives:
        name: "{{ alt_update.name }}"
        state: absent
      when:
        - ( alt_update.state is defined ) and ( alt_update.state == "absent" )
        - ansible_local.update_alternatives.selections[alt_update.name] is defined
      notify: Update ansible_local

    - name: Updates alternatives
      block:

        - name: Debug alt_update.alternatives
          ansible.builtin.debug:
            var: alt_update.alternatives
            verbosity: 2
          when: alt_update.alternatives is defined

        - name: Include remove or update alternative tasks
          ansible.builtin.include_tasks: update_alternative.yml
          loop: "{{ alt_update.alternatives }}"
          loop_control:
            loop_var: alternative
            label: "{{ alternative.alternative }}"

        - name: Reload ansible_local.alternatives facts
          ansible.builtin.meta: flush_handlers
          when: >
            ( ( alternative_removed is defined ) and ( alternative_removed.changed ) ) or
            ( ( alternative_updated is defined ) and ( alternative_updated.changed ) )

        - name: Set status for present link groups
          block:

            - name: Check set the link group to auto if was set to manual and should be set to auto
              ansible.builtin.debug:
                msg: "update-alternatives --auto {{ alt_update.name }}"
              when: ( ansible_check_mode ) or ( ansible_verbosity >= 1 )

            - name: Set the link group to auto if was set to manual and should be set to auto
              ansible.builtin.command: "update-alternatives --auto {{ alt_update.name }}"
              notify: Update ansible_local

          when:
            - ( alt_update.state is not defined ) or ( ( alt_update.state is defined ) and ( alt_update.state == "present" ) )
            - ( alt_update.status is defined ) and ( alt_update.status == "auto" )
            - ( ansible_local.update_alternatives.selections[alt_update.name] is defined )
            - ( ansible_local.update_alternatives.selections[alt_update.name].status == "manual" )

      when: ( alt_update.state is not defined ) or ( alt_update.state == "present" )

  tags:
    - alternatives
...
