---
- name: Debug slave
  ansible.builtin.debug:
    msg:
      - "alt_update.name {{ alt_update.name | quote }}"
      - "alt_update.link {{ alt_update.link | quote }}"
      - "alternative.alternative {{ alternative.alternative | quote }}"
      - "alt_slave.name {{ alt_slave.name | quote }}"
      - "alt_slave.path: {{ alt_slave.path | quote }}"
      - "slave.name {{ slave.name | quote }}"
      - "slave.path {{ slave.path | quote }}"
    verbosity: 2
  when: slave.name == alt_slave.name
  loop: "{{ alternative.slaves }}"
  loop_control:
    loop_var: alt_slave
    label: "{{ alt_slave.name }}"
  tags:
    - alternatives

- name: "Set a variable for the slaves part of the update-alternatives command for {{ alt_update.name }} alternative {{ alternative.alternative }}"
  ansible.builtin.set_fact:
    alternative_slaves: "{{ alternative_slaves | default('') }} --slave {{ alternative.alternative | quote }} {{ slave.name | quote }} {{ slave.path | quote }}"
  when:
    - slave.name == alt_slave.name
  loop: "{{ alternative.slaves }}"
  loop_control:
    loop_var: alt_slave
    label: "{{ alt_slave.name }}"
  tags:
    - alternatives
...
