---
- name: Update alternative
  block:

    - name: Update alternative
      ansible.builtin.command:
        cmd: >
          update-alternatives --install "{{ alt_update.link }}" "{{ alt_update.name }}" "{{ alternative.alternative }}" "{{ alternative.priority }}"
          {% if alternative.slaves is defined %}
            {% for slave in alternative.slaves %}
              --slave "{{ alt_update.link }}" "{{ slave.name }}" "{{ slave.path }}"
            {% endfor %}
          {% endif %}
      register: alternative_updated 

    - name: Debug update result standard out
      debug:
        var: alternative_updated.stdout 
        verbosity: 2
      when: alternative_updated.stdout is defined

    - name: Debug update result standard error
      debug:
        var: alternative_updated.stdout error 
        verbosity: 2
      when: alternative_updated.stdout is defined

  tags:
    - alternatives
...
