---
- name: Update alternatives
  block:

    - name: "Check alternative {{ alt_update.name }} absent"
      debug:
        msg: "update-alternatives --remove-all {{ alt_update.name }}"
      when:
        - ( ansible_check_mode ) or ( ansible_verbosity >= 1 )
        - ( alt_update.state is defined ) and ( alt_update.state == "absent" )

    - name: "Alternative {{ alt_update.name }} absent"
      ansible.builtin.command: "update-alternatives --remove-all {{ alt_update.name }}"
      when: ( alt_update.state is defined ) and ( alt_update.state == "absent" )

    - name: Updates alternatives
      block:

        - name: Debug alt_update.alternatives
          ansible.builtin.debug:
            var: alt_update.alternatives
            verbosity: 2
          when: alt_update.alternatives is defined

        - name: Include remove or update alternative tasks
          ansible.builtin.include_tasks: update_alternative.yml
          loop: "{{ alt_update.alternatives }}"
          loop_control:
            loop_var: alternative
            label: "{{ alternative.alternative }}"

        - name: Set status for present link groups
          block:

            - name: Check set the link group to auto if was set to manual and should be set to auto
              debug:
                msg: "update-alternatives --auto {{ alt_update.name }}"
              when: ( ansible_check_mode ) or ( ansible_verbosity >= 1 )

            - name: Set the link group to auto if was set to manual and should be set to auto
              ansible.builtin.command: "update-alternatives --auto {{ alt_update.name }}"

          when:
            - alt_update.state == "present"
            - alt_update.status == "auto"
            - ansible_local.update_alternatives.selections[alt_update.name] is defined
            - ansible_local.update_alternatives.selections[alt_update.name].status == "manual"

      when: ( alt_update.state is not defined ) or ( alt_update.state == "present" )

  tags:
    - alternatives
...
