---
- name: Update alternatives
  block:

    - name: "Alternative {{ alt.key }} absent"
      ansible.builtin.command: "update-alternatives --remove-all {{ alt.key }}"
      when: alt.value.state == "absent"

    - name: "Updates alternatives for {{ alt.key }}"
      block:

        - name: Remove alternatives
          ansible.builtin.command: "update-alternatives --remove {{ alt.key }} {{ alternative.path }}"
          loop: "{{ alt.value.alternatives }}"
          loop_control:
            loop_var: alternative
            label: "{{ alternative.path }}"
          when: alternative.state == "absent"

        - name: Debug alt.value.alternatives
          debug:
            var: alt.value.alternatives
            verbosity: 2
          when: alt.value.alternatives is defined

        - name: Include update alternative tasks
          ansible.builtin.include_tasks: update_alternative.yml
          loop: "{{ alt.value.alternatives }}"
          loop_control:
            loop_var: alternative
            label: "{{ alternative.path }}"
          when: alternative.state == "present"

        - name: Set the link group to auto if was set to manual
          ansible.builtin.command: "update-alternatives --auto {{ alt.key }}"
          when: ansible_local.alternatives[alt.key].status == "manual"

      when: alt.value.state == "present"

  tags:
    - alternatives
...
